const codes: Partial<Record<string, string>> = {
	//From Quizlet
	EASE: 'Active aggressor/active shooter event',
	EBERT: 'ALS alarm BERT Medical',
	EASS: 'ALS assault',
	EAIP: 'ALS assault in progress',
	EAST: 'ALS asthma',
	EBUV: 'ALS burn victum',
	ECHP: 'ALS chest pain',
	ECHO: 'ALS choking',
	ECOD: 'ALS code blue',
	ECOR: 'ALS coronary',
	ECUT: 'ALS cutting/stabbing',
	EDIA: 'ALS diabetic',
	EDIB: 'ALS difficulty breathing',
	EDRO: 'ALS drowning',
	EELC: 'ALS electric shock',
	EELE: 'ALS elevator emergency',
	EEMT: 'ALS emergency transfer',
	EDET: 'ALS EMS detail',
	EOTH: 'ALS EMS other',
	EFAI: 'ALS fainted',
	EIDP: 'ALS infectious disease protocol',
	EIFF: 'ALS injured from fall ( over ten feet)',
	EINP: 'ALS injured person',
	ELOI: 'ALS lock in/lock out with medical emergency',
	EMAT: 'ALS maternity',
	EMCI: 'ALS MCI- only use for upgrade',
	EOVD: 'ALS overdose/poisoning',
	EPSY: 'ALS psychological',
	EMER: 'ALS radio emergency',
	EPD7: 'ALS reduced response radio emergency',
	ESEI: 'ALS seizure',
	ESHO: 'ALS shock',
	ESHT: 'ALS shooting /gunshot wound',
	ESIC: 'ALS sick case',
	ESOW: 'ALS slumped over the wheel',
	ESMI: 'ALS smoke inhalation',
	ESTR: 'ALS stroke/CVA',
	ESUD: 'ALS subject down',
	ESUA: 'ALS suicide attempt/threat',
	EUNC: 'ALS unconscious person',
	EUNT: 'ALS unknown trouble (EMS)',
	EUNR: 'ALS unresponsive person',
	EVIS: 'ALS vehicle in a structure',
	EVEA: 'ALS vehicle accident',
	EVAM: 'ALS vehicle accident (minor)',
	EVAJ: 'ALS vehicle accident with JAWS',
	FAA1: 'Air craft alert 1',
	FAA2: 'Air craft alert 2',
	FAA3: 'Air craft alert 3',
	FASB: 'Aircraft standby bluegrass station',
	FASS: 'Assistance',
	FBAS: 'Barricaded subject',
	FBOT: 'Bomb threat',
	FBWD: 'Bomb threat with a device',
	FBGL: 'Brush/grass/leaf/tree fire',
	FBERTR: 'BERT- rescue',
	FBERTH: 'BERT- HAZMAT- notify shift commander before dispatch',
	FCMS: 'Carbon monoxide sickness',
	FCAR: 'Carbon monoxide situation',
	FCHI: 'Chimney fire',
	FCOL: 'Collapse rescue',
	FCSEPP: 'Community emergency- bluegrass army depot',
	FCSR: 'Confined space rescue',
	FDVR: 'Dive rescue response',
	FDUM: 'Dumpster fire',
	FELC: 'Electrical cutoff',
	FELF: 'Electrical fire',
	FELS: 'Elevator situation',
	FEXP: 'Explosion',
	FFIA: 'Fire in an appliance',
	FGAC: 'Gas cutoff',
	FGAS: 'Gasoline/fuel leak',
	FHMC: 'Hazardous material',
	FSCU: 'HAZMAT- MVC general spill cleanup',
	FHCL: 'HAZMAT- clandestine lab',
	FMERC: 'HAZMAT- mercury spill',
	FHGEO: 'HAZMAT- natural gas from geothermal/water well',
	FINV: 'Investigation',
	FLAR: 'Large animal rescue',
	FLIFT: 'Lift assist',
	FLOI: 'Lock in/lock out',
	FMAI: 'Mailbox fire',
	FMDR: 'Mass Decon response- Kroger field',
	FMIS: 'Missing person',
	FNGL: 'Natural gas leak ( natural gas and propane)',
	FGAO: 'Natural gas odor ( natural gas or propane)',
	FOTS: 'Other service',
	FK9R: 'Out of county investigation k-9 response',
	FPRT: 'Private/telephone alarm',
	FFLB: 'Reduced response',
	FWAR: 'Remove water',
	FROP: 'Rope/high angle rescue',
	FSIA: 'Smoke in the area - outdoors',
	FSMO: 'Smoke in the area/structure/odor',
	FSRCU: 'Special rescue realtor to civil unrest',
	FSTR: 'Structure fire',
	FSTRW: 'Structure fire- working',
	FTRA: 'Train accident',
	FTRN: 'Transformer fire',
	FTRS: 'Trash fire',
	FTRE: 'Trench rescue',
	FUNT: 'Unknown trouble',
	FVIS: 'Vehicle in a structure',
	FVAJ: 'Vehicle accident with JAWS',
	FVEH: 'Vehicle fire',
	FVNS: 'Vehicle fire near a structure',
	FVLA: 'Vehicle fire large vehicle',
	FWAC: 'Water cutoff',
	FWTR: 'Water rescue',
	FWID: 'Wires down',

	//Added by me
	MED: 'Medical'
};

export default codes;
